<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210804220850 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE contest_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contest_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE data_fixture_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE egg_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE evolution_chain_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE generation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE growth_rate_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_fling_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_name_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_pocket_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE machine_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_damage_class_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_learn_method_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_name_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_target_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_availability_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_color_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_egg_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_habitat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_move_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_name_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_shape_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_specy_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_type_past_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE specy_name_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE contest_effect (id INT NOT NULL, appeal INT NOT NULL, jam INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE contest_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE data_fixture (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE egg_group (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE evolution_chain (id INT NOT NULL, baby_trigger_item_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_68B11268362317DB ON evolution_chain (baby_trigger_item_id)');
        $this->addSql('CREATE TABLE generation (id INT NOT NULL, name VARCHAR(255) NOT NULL, generation_identifier INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE growth_rate (id INT NOT NULL, formula VARCHAR(1000) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE item (id INT NOT NULL, item_fling_effect_id INT DEFAULT NULL, item_category_id INT NOT NULL, name VARCHAR(255) NOT NULL, fling_power INT DEFAULT NULL, cost INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F1B251EC1EBCA1B ON item (item_fling_effect_id)');
        $this->addSql('CREATE INDEX IDX_1F1B251EF22EC5D4 ON item (item_category_id)');
        $this->addSql('CREATE TABLE item_category (id INT NOT NULL, item_pocket_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A41D10AE75909A9 ON item_category (item_pocket_id)');
        $this->addSql('CREATE TABLE item_fling_effect (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE item_name (id INT NOT NULL, item_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, language INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_96133AFD126F525E ON item_name (item_id)');
        $this->addSql('CREATE TABLE item_pocket (id INT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE machine (id INT NOT NULL, move_id INT DEFAULT NULL, item_id INT DEFAULT NULL, version_group_id INT NOT NULL, growth_rate_id INT DEFAULT NULL, machine_number INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1505DF846DC541A8 ON machine (move_id)');
        $this->addSql('CREATE INDEX IDX_1505DF84126F525E ON machine (item_id)');
        $this->addSql('CREATE INDEX IDX_1505DF8492AE854F ON machine (version_group_id)');
        $this->addSql('CREATE INDEX IDX_1505DF84DA36863D ON machine (growth_rate_id)');
        $this->addSql('CREATE TABLE move (id INT NOT NULL, generation_id INT NOT NULL, move_damage_class_id INT DEFAULT NULL, contest_effect_id INT DEFAULT NULL, move_target_id INT NOT NULL, contest_type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, accuracy INT DEFAULT NULL, move_effect_chance INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EF3E3778553A6EC4 ON move (generation_id)');
        $this->addSql('CREATE INDEX IDX_EF3E3778F72F9F17 ON move (move_damage_class_id)');
        $this->addSql('CREATE INDEX IDX_EF3E377857B91C2A ON move (contest_effect_id)');
        $this->addSql('CREATE INDEX IDX_EF3E3778927355BD ON move (move_target_id)');
        $this->addSql('CREATE INDEX IDX_EF3E3778C8145F78 ON move (contest_type_id)');
        $this->addSql('CREATE TABLE move_damage_class (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_effect (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_learn_method (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_name (id INT NOT NULL, move_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, language INT NOT NULL, gen1 VARCHAR(255) DEFAULT NULL, gen2 VARCHAR(255) DEFAULT NULL, gen3 VARCHAR(255) DEFAULT NULL, gen4 VARCHAR(255) DEFAULT NULL, gen5 VARCHAR(255) DEFAULT NULL, gen6 VARCHAR(255) DEFAULT NULL, gen7 VARCHAR(255) DEFAULT NULL, gen8 VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_504B42B26DC541A8 ON move_name (move_id)');
        $this->addSql('CREATE TABLE move_target (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon (id INT NOT NULL, pokemon_specy_id INT NOT NULL, pokemon_name_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, is_alola BOOLEAN NOT NULL, is_galar BOOLEAN NOT NULL, is_default BOOLEAN NOT NULL, has_move_forms BOOLEAN NOT NULL, base_experience INT NOT NULL, height INT NOT NULL, pokemon_order INT NOT NULL, weight INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_62DC90F3256D30DF ON pokemon (pokemon_specy_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_62DC90F31D7DE047 ON pokemon (pokemon_name_id)');
        $this->addSql('CREATE TABLE pokemon_pokemon (pokemon_source INT NOT NULL, pokemon_target INT NOT NULL, PRIMARY KEY(pokemon_source, pokemon_target))');
        $this->addSql('CREATE INDEX IDX_EB6EC6233630327 ON pokemon_pokemon (pokemon_source)');
        $this->addSql('CREATE INDEX IDX_EB6EC622A8653A8 ON pokemon_pokemon (pokemon_target)');
        $this->addSql('CREATE TABLE pokemon_availability (id INT NOT NULL, pokemon_id INT NOT NULL, version_group_id INT NOT NULL, availability BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7E30D9662FE71C3E ON pokemon_availability (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_7E30D96692AE854F ON pokemon_availability (version_group_id)');
        $this->addSql('CREATE TABLE pokemon_color (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_egg_group (id INT NOT NULL, egg_group_id INT NOT NULL, pokemon_specy_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_311E850B76DC94C ON pokemon_egg_group (egg_group_id)');
        $this->addSql('CREATE INDEX IDX_311E850256D30DF ON pokemon_egg_group (pokemon_specy_id)');
        $this->addSql('CREATE TABLE pokemon_habitat (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_move (id INT NOT NULL, move_id INT NOT NULL, version_group_id INT NOT NULL, learn_method_id INT NOT NULL, pokemon_id INT NOT NULL, level INT DEFAULT NULL, pokemon_move_order INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D397493B6DC541A8 ON pokemon_move (move_id)');
        $this->addSql('CREATE INDEX IDX_D397493B92AE854F ON pokemon_move (version_group_id)');
        $this->addSql('CREATE INDEX IDX_D397493B764E5F26 ON pokemon_move (learn_method_id)');
        $this->addSql('CREATE INDEX IDX_D397493B2FE71C3E ON pokemon_move (pokemon_id)');
        $this->addSql('CREATE TABLE pokemon_name (id INT NOT NULL, bulbapedia_name VARCHAR(255) NOT NULL, pokepedia_name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_shape (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_specy (id INT NOT NULL, evolution_chain_id INT DEFAULT NULL, generation_id INT NOT NULL, growth_rate_id INT NOT NULL, pokemon_shape_id INT NOT NULL, pokemon_habitat_id INT DEFAULT NULL, pokemon_color_id INT NOT NULL, evolve_from_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, base_hapiness INT NOT NULL, capture_rate INT NOT NULL, forms_switchable BOOLEAN NOT NULL, gender_rate INT NOT NULL, has_gender_differences BOOLEAN NOT NULL, hatch_counter INT NOT NULL, is_baby BOOLEAN NOT NULL, is_legendary BOOLEAN NOT NULL, is_mythical BOOLEAN NOT NULL, pokemon_specy_order INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D5938CFDE417AC09 ON pokemon_specy (evolution_chain_id)');
        $this->addSql('CREATE INDEX IDX_D5938CFD553A6EC4 ON pokemon_specy (generation_id)');
        $this->addSql('CREATE INDEX IDX_D5938CFDDA36863D ON pokemon_specy (growth_rate_id)');
        $this->addSql('CREATE INDEX IDX_D5938CFDD742A515 ON pokemon_specy (pokemon_shape_id)');
        $this->addSql('CREATE INDEX IDX_D5938CFD7DC24131 ON pokemon_specy (pokemon_habitat_id)');
        $this->addSql('CREATE INDEX IDX_D5938CFDFDBED61B ON pokemon_specy (pokemon_color_id)');
        $this->addSql('CREATE INDEX IDX_D5938CFD47DB1A77 ON pokemon_specy (evolve_from_id)');
        $this->addSql('CREATE TABLE pokemon_type (id INT NOT NULL, pokemon_id INT DEFAULT NULL, type_id INT NOT NULL, slot INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B077296A2FE71C3E ON pokemon_type (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_B077296AC54C8C93 ON pokemon_type (type_id)');
        $this->addSql('CREATE TABLE pokemon_type_past (id INT NOT NULL, pokemon_id INT NOT NULL, type_id INT NOT NULL, generation_id INT NOT NULL, slot INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B6F26EA92FE71C3E ON pokemon_type_past (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_B6F26EA9C54C8C93 ON pokemon_type_past (type_id)');
        $this->addSql('CREATE INDEX IDX_B6F26EA9553A6EC4 ON pokemon_type_past (generation_id)');
        $this->addSql('CREATE TABLE specy_name (id INT NOT NULL, pokemon_specy_id INT NOT NULL, name VARCHAR(255) NOT NULL, language INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C50BC896256D30DF ON specy_name (pokemon_specy_id)');
        $this->addSql('CREATE TABLE type (id INT NOT NULL, generation_id INT DEFAULT NULL, move_damage_class_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8CDE5729553A6EC4 ON type (generation_id)');
        $this->addSql('CREATE INDEX IDX_8CDE5729F72F9F17 ON type (move_damage_class_id)');
        $this->addSql('CREATE TABLE version_group (id INT NOT NULL, generation_id INT NOT NULL, name VARCHAR(255) NOT NULL, version_group_order INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A1C90C0553A6EC4 ON version_group (generation_id)');
        $this->addSql('ALTER TABLE evolution_chain ADD CONSTRAINT FK_68B11268362317DB FOREIGN KEY (baby_trigger_item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251EC1EBCA1B FOREIGN KEY (item_fling_effect_id) REFERENCES item_fling_effect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251EF22EC5D4 FOREIGN KEY (item_category_id) REFERENCES item_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_category ADD CONSTRAINT FK_6A41D10AE75909A9 FOREIGN KEY (item_pocket_id) REFERENCES item_pocket (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_name ADD CONSTRAINT FK_96133AFD126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE machine ADD CONSTRAINT FK_1505DF846DC541A8 FOREIGN KEY (move_id) REFERENCES move (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE machine ADD CONSTRAINT FK_1505DF84126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE machine ADD CONSTRAINT FK_1505DF8492AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE machine ADD CONSTRAINT FK_1505DF84DA36863D FOREIGN KEY (growth_rate_id) REFERENCES growth_rate (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778F72F9F17 FOREIGN KEY (move_damage_class_id) REFERENCES move_damage_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E377857B91C2A FOREIGN KEY (contest_effect_id) REFERENCES contest_effect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778927355BD FOREIGN KEY (move_target_id) REFERENCES move_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move ADD CONSTRAINT FK_EF3E3778C8145F78 FOREIGN KEY (contest_type_id) REFERENCES contest_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_name ADD CONSTRAINT FK_504B42B26DC541A8 FOREIGN KEY (move_id) REFERENCES move (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3256D30DF FOREIGN KEY (pokemon_specy_id) REFERENCES pokemon_specy (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F31D7DE047 FOREIGN KEY (pokemon_name_id) REFERENCES pokemon_name (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_pokemon ADD CONSTRAINT FK_EB6EC6233630327 FOREIGN KEY (pokemon_source) REFERENCES pokemon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_pokemon ADD CONSTRAINT FK_EB6EC622A8653A8 FOREIGN KEY (pokemon_target) REFERENCES pokemon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_availability ADD CONSTRAINT FK_7E30D9662FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_availability ADD CONSTRAINT FK_7E30D96692AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_egg_group ADD CONSTRAINT FK_311E850B76DC94C FOREIGN KEY (egg_group_id) REFERENCES egg_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_egg_group ADD CONSTRAINT FK_311E850256D30DF FOREIGN KEY (pokemon_specy_id) REFERENCES pokemon_specy (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B6DC541A8 FOREIGN KEY (move_id) REFERENCES move (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B764E5F26 FOREIGN KEY (learn_method_id) REFERENCES move_learn_method (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFDE417AC09 FOREIGN KEY (evolution_chain_id) REFERENCES evolution_chain (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFD553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFDDA36863D FOREIGN KEY (growth_rate_id) REFERENCES growth_rate (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFDD742A515 FOREIGN KEY (pokemon_shape_id) REFERENCES pokemon_shape (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFD7DC24131 FOREIGN KEY (pokemon_habitat_id) REFERENCES pokemon_habitat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFDFDBED61B FOREIGN KEY (pokemon_color_id) REFERENCES pokemon_color (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_specy ADD CONSTRAINT FK_D5938CFD47DB1A77 FOREIGN KEY (evolve_from_id) REFERENCES pokemon_specy (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type ADD CONSTRAINT FK_B077296A2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type ADD CONSTRAINT FK_B077296AC54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type_past ADD CONSTRAINT FK_B6F26EA92FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type_past ADD CONSTRAINT FK_B6F26EA9C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type_past ADD CONSTRAINT FK_B6F26EA9553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE specy_name ADD CONSTRAINT FK_C50BC896256D30DF FOREIGN KEY (pokemon_specy_id) REFERENCES pokemon_specy (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE5729553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE5729F72F9F17 FOREIGN KEY (move_damage_class_id) REFERENCES move_damage_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE version_group ADD CONSTRAINT FK_6A1C90C0553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E377857B91C2A');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778C8145F78');
        $this->addSql('ALTER TABLE pokemon_egg_group DROP CONSTRAINT FK_311E850B76DC94C');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFDE417AC09');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778553A6EC4');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFD553A6EC4');
        $this->addSql('ALTER TABLE pokemon_type_past DROP CONSTRAINT FK_B6F26EA9553A6EC4');
        $this->addSql('ALTER TABLE type DROP CONSTRAINT FK_8CDE5729553A6EC4');
        $this->addSql('ALTER TABLE version_group DROP CONSTRAINT FK_6A1C90C0553A6EC4');
        $this->addSql('ALTER TABLE machine DROP CONSTRAINT FK_1505DF84DA36863D');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFDDA36863D');
        $this->addSql('ALTER TABLE evolution_chain DROP CONSTRAINT FK_68B11268362317DB');
        $this->addSql('ALTER TABLE item_name DROP CONSTRAINT FK_96133AFD126F525E');
        $this->addSql('ALTER TABLE machine DROP CONSTRAINT FK_1505DF84126F525E');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251EF22EC5D4');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251EC1EBCA1B');
        $this->addSql('ALTER TABLE item_category DROP CONSTRAINT FK_6A41D10AE75909A9');
        $this->addSql('ALTER TABLE machine DROP CONSTRAINT FK_1505DF846DC541A8');
        $this->addSql('ALTER TABLE move_name DROP CONSTRAINT FK_504B42B26DC541A8');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B6DC541A8');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778F72F9F17');
        $this->addSql('ALTER TABLE type DROP CONSTRAINT FK_8CDE5729F72F9F17');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B764E5F26');
        $this->addSql('ALTER TABLE move DROP CONSTRAINT FK_EF3E3778927355BD');
        $this->addSql('ALTER TABLE pokemon_pokemon DROP CONSTRAINT FK_EB6EC6233630327');
        $this->addSql('ALTER TABLE pokemon_pokemon DROP CONSTRAINT FK_EB6EC622A8653A8');
        $this->addSql('ALTER TABLE pokemon_availability DROP CONSTRAINT FK_7E30D9662FE71C3E');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_type DROP CONSTRAINT FK_B077296A2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_type_past DROP CONSTRAINT FK_B6F26EA92FE71C3E');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFDFDBED61B');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFD7DC24131');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F31D7DE047');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFDD742A515');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F3256D30DF');
        $this->addSql('ALTER TABLE pokemon_egg_group DROP CONSTRAINT FK_311E850256D30DF');
        $this->addSql('ALTER TABLE pokemon_specy DROP CONSTRAINT FK_D5938CFD47DB1A77');
        $this->addSql('ALTER TABLE specy_name DROP CONSTRAINT FK_C50BC896256D30DF');
        $this->addSql('ALTER TABLE pokemon_type DROP CONSTRAINT FK_B077296AC54C8C93');
        $this->addSql('ALTER TABLE pokemon_type_past DROP CONSTRAINT FK_B6F26EA9C54C8C93');
        $this->addSql('ALTER TABLE machine DROP CONSTRAINT FK_1505DF8492AE854F');
        $this->addSql('ALTER TABLE pokemon_availability DROP CONSTRAINT FK_7E30D96692AE854F');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B92AE854F');
        $this->addSql('DROP SEQUENCE contest_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contest_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE data_fixture_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE egg_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE evolution_chain_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE generation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE growth_rate_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_fling_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_name_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_pocket_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE machine_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_damage_class_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_learn_method_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_name_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_target_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_availability_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_color_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_egg_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_habitat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_move_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_name_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_shape_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_specy_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_type_past_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE specy_name_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE version_group_id_seq CASCADE');
        $this->addSql('DROP TABLE contest_effect');
        $this->addSql('DROP TABLE contest_type');
        $this->addSql('DROP TABLE data_fixture');
        $this->addSql('DROP TABLE egg_group');
        $this->addSql('DROP TABLE evolution_chain');
        $this->addSql('DROP TABLE generation');
        $this->addSql('DROP TABLE growth_rate');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_category');
        $this->addSql('DROP TABLE item_fling_effect');
        $this->addSql('DROP TABLE item_name');
        $this->addSql('DROP TABLE item_pocket');
        $this->addSql('DROP TABLE machine');
        $this->addSql('DROP TABLE move');
        $this->addSql('DROP TABLE move_damage_class');
        $this->addSql('DROP TABLE move_effect');
        $this->addSql('DROP TABLE move_learn_method');
        $this->addSql('DROP TABLE move_name');
        $this->addSql('DROP TABLE move_target');
        $this->addSql('DROP TABLE pokemon');
        $this->addSql('DROP TABLE pokemon_pokemon');
        $this->addSql('DROP TABLE pokemon_availability');
        $this->addSql('DROP TABLE pokemon_color');
        $this->addSql('DROP TABLE pokemon_egg_group');
        $this->addSql('DROP TABLE pokemon_habitat');
        $this->addSql('DROP TABLE pokemon_move');
        $this->addSql('DROP TABLE pokemon_name');
        $this->addSql('DROP TABLE pokemon_shape');
        $this->addSql('DROP TABLE pokemon_specy');
        $this->addSql('DROP TABLE pokemon_type');
        $this->addSql('DROP TABLE pokemon_type_past');
        $this->addSql('DROP TABLE specy_name');
        $this->addSql('DROP TABLE type');
        $this->addSql('DROP TABLE version_group');
    }
}
