moves:
  level:
    7:
      global:
        lets-go:
          - learnlist
          - level
          - move
  tutor:
    7:
      global:
        lets-go:
          - learnlist
          - move
  machine:
    7:
      global:
        lets-go:
         - learnlist
         - machine
         - move


