moves:
  level:
    7:
      global:
        lets-go:
          - learnlist
          - level
          - move
    8:
      global:
        sword-shield:
          - learnlist
          - level
          - move
  tutor:
    7:
      global:
        lets-go:
          - learnlist
          - move
  tm:
    7:
      global:
        lets-go:
         - learnlist
         - machine
         - move
    8:
      global:
        sword-shield:
         - learnlist
         - machine
         - move
  breed:
    8:
      global:
        sword-shield:
         - learnlist
         - parents
         - move



